# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ca5647f8007cd324b286beeeef81bf0f754102644c5e493470a2e048f6876ceba79be0a71b1853271d511c203db65036729e4d525b8ae3da837cd083b687381

test:
  secret_key_base: 32177dc48f56b3a867bdffbb5071206423d4b09fc3c0bf9a8fa58f98700d8100c976b19341b48908292efe103b56c73d78a6775cd108b8e998bae606a1055938

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
